version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    container_name: official-developer-docs
    ports:
      - '8080:80'